version: 2

project_name: poltergeist

env:
  - VECTORSCAN_VERSION=5.4.11

before:
  hooks:
    - go mod tidy
    - bash scripts/build-vectorscan.sh

builds:
  - id: poltergeist
    main: ./cmd/poltergeist
    binary: poltergeist
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

    # Platform-specific build settings for static linking
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=gcc
          - CGO_CFLAGS=-I{{.Env.PWD}}/build/vectorscan/linux_amd64/include
          - CGO_LDFLAGS=-L{{.Env.PWD}}/build/vectorscan/linux_amd64/lib -lhs -lstdc++ -lm
        flags:
          - -a
        ldflags:
          - -s -w
          - -X main.version={{.Version}}
          - -linkmode external
          - -extldflags "-static"

      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc
          - CGO_CFLAGS=-I{{.Env.PWD}}/build/vectorscan/linux_arm64/include
          - CGO_LDFLAGS=-L{{.Env.PWD}}/build/vectorscan/linux_arm64/lib -lhs -lstdc++ -lm
        flags:
          - -a
        ldflags:
          - -s -w
          - -X main.version={{.Version}}
          - -linkmode external
          - -extldflags "-static"

      - goos: darwin
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CGO_CFLAGS=-I{{.Env.PWD}}/build/vectorscan/darwin_amd64/include
          - CGO_LDFLAGS=-L{{.Env.PWD}}/build/vectorscan/darwin_amd64/lib -lhs -lc++
        ldflags:
          - -s -w
          - -X main.version={{.Version}}

      - goos: darwin
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CGO_CFLAGS=-I{{.Env.PWD}}/build/vectorscan/darwin_arm64/include
          - CGO_LDFLAGS=-L{{.Env.PWD}}/build/vectorscan/darwin_arm64/lib -lhs -lc++
        ldflags:
          - -s -w
          - -X main.version={{.Version}}

archives:
  - id: default
    formats: ['tar.gz']
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE
      - NOTICE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: ghostsecurity
    name: poltergeist
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
